### ISSUE TITLE
Did you disable search?

### ISSUE THREAD

**Issue by x10an14** [syedzayyan/shadharon#11]
I can't seem to get search to work, nor do I find any css references to it in this repo's files.

Tried by adding the following to `config.toml`:
```toml
 # Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"
[search]
include_title = true
include_description = true
```
